# Generated by Django 5.1.6 on 2025-02-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_IsisTime', '0002_ponto_delete_registroponto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='ponto',
            name='data_hora',
            field=models.DateTimeField(),
        ),
    ]
